# Generated by Django 4.0.3 on 2022-05-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_costmodel_request_cost_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='cost_model',
        ),
        migrations.AddField(
            model_name='request',
            name='cost_model',
            field=models.ManyToManyField(to='main.costmodel'),
        ),
    ]
