# Generated by Django 4.0.3 on 2022-05-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_request_cost_model_request_cost_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
